[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = "cancun"
via_ir = false
optimizer_runs = 800
ffi = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
